language: csharp
dotnet: 2.1.4
script:
  - dotnet restore
  - dotnet build
  - nuget push ./SqlHelper/bin/Release/SqlWrapperLite.*.nupkg -Verbosity detailed -ApiKey $NUGET_API_KEY -Source $NUGET_SOURCE
deploy:
  skip_cleanup: true
  on:
    branch: master
